[package]
name = "gks-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
noodles-vcf = { version = "0.65.0", features = ["async"] }
sha2 = "0.10.8"
clap = { version = "4.5.17", features = ["derive"] }
futures = "0.3.30"
itertools = "0.13.0"
